INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3039163, 'AD', 'Andorra', 'Андорра', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (290557, 'AE', 'United Arab Emirates', 'ОАЭ', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1121143, 'AF', 'Afghanistan', 'Афганистан', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3576022, 'AG', 'Antigua and Barbuda', 'Антигуа и Барбуда', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3573374, 'AI', 'Anguilla', 'Ангилья', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (363243, 'AL', 'Albania', 'Албания', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (174875, 'AM', 'Armenia', 'Армения', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (145531, 'AO', 'Angola', 'Ангола', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (6697173, 'AQ', 'Antarctica', 'Антарктида', 2);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3427213, 'AR', 'Argentina', 'Аргентина', 7);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (5880801, 'AS', 'American Samoa', 'Американское Самоа', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2599046, 'AT', 'Austria', 'Австрия', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2057277, 'AU', 'Australia', 'Австралия', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3577097, 'AW', 'Aruba', 'Аруба', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (635815, 'AX', 'Åland', 'Аланды', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (147271, 'AZ', 'Azerbaijan', 'Азербайджан', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3186246, 'BA', 'Bosnia and Herzegovina', 'Босния', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3373408, 'BB', 'Barbados', 'Барбадос', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1185093, 'BD', 'Bangladesh', 'Бангладеш', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2783081, 'BE', 'Belgium', 'Бельгия', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2357048, 'BF', 'Burkina Faso', 'Буркина Фасо', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (725213, 'BG', 'Bulgaria', 'Болгария', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (290087, 'BH', 'Bahrain', 'Бахрейн', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (425378, 'BI', 'Burundi', 'Бурунди', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2392087, 'BJ', 'Benin', 'Бенин', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3578476, 'BL', 'Saint-Barthélemy', 'Остров Святого Бартоломея', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3573029, 'BM', 'Bermuda', 'Бермудские о-ва', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1820071, 'BN', 'Brunei', 'Бруней Даруссалам', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3902377, 'BO', 'Bolivia', 'Боливия', 7);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3513083, 'BQ', 'Bonaire, Sint Eustatius, and Saba', 'Бонайре, Синт-Эстатиус и Саба', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3384930, 'BR', 'Brazil', 'Бразилия', 7);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3571824, 'BS', 'Bahamas', 'Багамы', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1252416, 'BT', 'Bhutan', 'Бутан', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (933004, 'BW', 'Botswana', 'Ботсвана', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (618800, 'BY', 'Belarus', 'Беларусь', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3581164, 'BZ', 'Belize', 'Белиз', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (5881639, 'CA', 'Canada', 'Канада', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1547376, 'CC', 'Cocos [Keeling] Islands', 'Кокосовые о-ва', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (203312, 'CD', 'Congo', 'Заир', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (239880, 'CF', 'Central African Republic', 'ЦАР', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2255329, 'CG', 'Republic of the Congo', 'Конго', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2657886, 'CH', 'Switzerland', 'Швейцария', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2282335, 'CI', 'Ivory Coast', 'Кот-д''Ивуар', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1899402, 'CK', 'Cook Islands', 'Острова Кука', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3867625, 'CL', 'Chile', 'Чили', 7);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2220957, 'CM', 'Cameroon', 'Камерун', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1279685, 'CN', 'China', 'Китай', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3665542, 'CO', 'Colombia', 'Колумбия', 7);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3620992, 'CR', 'Costa Rica', 'Коста-Рика', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3534632, 'CU', 'Cuba', 'Куба', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3374275, 'CV', 'Cape Verde', 'Острова Зеленого Мыса', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3513090, 'CW', 'Curaçao', 'Кюрасао', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2078127, 'CX', 'Christmas Island', 'Остров Рождества', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (145952, 'CY', 'Cyprus', 'Кипр', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3061284, 'CZ', 'Czechia', 'Чешская Республика', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2803474, 'DE', 'Germany', 'Германия', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (223816, 'DJ', 'Djibouti', 'Джибути', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2609990, 'DK', 'Denmark', 'Дания', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3575635, 'DM', 'Dominica', 'Остров Доминика', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3491922, 'DO', 'Dominican Republic', 'Доминиканская Республика', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2475475, 'DZ', 'Algeria', 'Алжир', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3649959, 'EC', 'Ecuador', 'Эквадор', 7);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (453733, 'EE', 'Estonia', 'Эстония', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (345995, 'EG', 'Egypt', 'Египет', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (338010, 'ER', 'Eritrea', 'Эритрея', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2509305, 'ES', 'Spain', 'Испания', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (326282, 'ET', 'Ethiopia', 'Эфиопия', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (630736, 'FI', 'Finland', 'Финляндия', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2198148, 'FJ', 'Fiji', 'Фиджи', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3426691, 'FK', 'Falkland Islands', 'Фолклендские о-ва', 7);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2081175, 'FM', 'Federated States of Micronesia', 'Микронезия', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2611060, 'FO', 'Faroe Islands', 'Фарерские о-ва', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2967108, 'FR', 'France', 'Франция', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2396518, 'GA', 'Gabon', 'Габон', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2633326, 'GB', 'United Kingdom', 'Великобритания', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3579833, 'GD', 'Grenada', 'Гренада', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (610824, 'GE', 'Georgia', 'Грузия', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3380892, 'GF', 'French Guiana', 'Французская Гвиана', 7);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3042287, 'GG', 'Guernsey', 'Гернси', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2294034, 'GH', 'Ghana', 'Гана', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2411585, 'GI', 'Gibraltar', 'Гибралтар', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3419842, 'GL', 'Greenland', 'Гренландия', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2413106, 'GM', 'Gambia', 'Гамбия', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2415703, 'GN', 'Guinea', 'Гвинея', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3578278, 'GP', 'Guadeloupe', 'Гваделупа', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2306898, 'GQ', 'Equatorial Guinea', 'Экваториальная Гвинея', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (251261, 'GR', 'Greece', 'Греция', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3426466, 'GS', 'South Georgia and the South Sandwich Islands', 'Южная Джорджия и Южные Сандвичевы Острова', 2);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3587543, 'GT', 'Guatemala', 'Гватемала', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (4038554, 'GU', 'Guam', 'Гуам', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2372248, 'GW', 'Guinea-Bissau', 'Гвинея-Биссау', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3377408, 'GY', 'Guyana', 'Гайана', 7);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1818209, 'HK', 'Hong Kong', 'Гонконг', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3600026, 'HN', 'Honduras', 'Гондурас', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3186294, 'HR', 'Croatia', 'Хорватия', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3716151, 'HT', 'Haiti', 'Гаити', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (713836, 'HU', 'Hungary', 'Венгрия', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1213499, 'ID', 'Indonesia', 'Индонезия', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2654332, 'IE', 'Ireland', 'Ирландия', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (281184, 'IL', 'Israel', 'Израиль', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3042182, 'IM', 'Isle of Man', 'Мэн, о-в', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1252758, 'IN', 'India', 'Индия', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1282588, 'IO', 'British Indian Ocean Territory', 'Британская территория в Индийском океане', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (90552, 'IQ', 'Iraq', 'Ирак', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (110791, 'IR', 'Iran', 'Иран', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2627130, 'IS', 'Iceland', 'Исландия', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2522685, 'IT', 'Italy', 'Италия', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3042089, 'JE', 'Jersey', 'Джерси', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3488465, 'JM', 'Jamaica', 'Ямайка', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (247068, 'JO', 'Hashemite Kingdom of Jordan', 'Иордания', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1847947, 'JP', 'Japan', 'Япония', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (179330, 'KE', 'Kenya', 'Кения', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1527004, 'KG', 'Kyrgyzstan', 'Кыргызстан', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1821306, 'KH', 'Cambodia', 'Камбоджа', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2110141, 'KI', 'Kiribati', 'Кирибати', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (921721, 'KM', 'Comoros', 'Коморские о-ва', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3575167, 'KN', 'Saint Kitts and Nevis', 'Сент-Киттс и Невис', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1871859, 'KP', 'North Korea', 'Северная Корея', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1832034, 'KR', 'Republic of Korea', 'Южная Корея', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (285570, 'KW', 'Kuwait', 'Кувейт', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3580477, 'KY', 'Cayman Islands', 'Каймановы Острова', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (607610, 'KZ', 'Kazakhstan', 'Казахстан', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1651944, 'LA', 'Laos', 'Лаос', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (266045, 'LB', 'Lebanon', 'Ливан', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3576414, 'LC', 'Saint Lucia', 'Сент-Люсия', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3042030, 'LI', 'Liechtenstein', 'Лихтенштейн', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1223421, 'LK', 'Sri Lanka', 'Шри-Ланка', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2274465, 'LR', 'Liberia', 'Либерия', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (932150, 'LS', 'Lesotho', 'Лесото', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (592787, 'LT', 'Republic of Lithuania', 'Литва', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2959959, 'LU', 'Luxembourg', 'Люксембург', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (453754, 'LV', 'Latvia', 'Латвия', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (88319, 'LY', 'Libya', 'Ливия', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2526092, 'MA', 'Morocco', 'Марокко', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2992741, 'MC', 'Monaco', 'Монако', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (617076, 'MD', 'Republic of Moldova', 'Молдова', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3193044, 'ME', 'Montenegro', 'Черногория', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3578421, 'MF', 'Saint Martin', 'Остров Святого Мартина', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1053384, 'MG', 'Madagascar', 'Мадагаскар', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2080185, 'MH', 'Marshall Islands', 'Маршалловы о-ва', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (718075, 'MK', 'Macedonia', 'Македония', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2453866, 'ML', 'Mali', 'Мали', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1289911, 'MM', 'Myanmar [Burma]', 'Мьянма', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1515404, 'MN', 'Mongolia', 'Монголия', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1821263, 'MO', 'Macao', 'Макао', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (4041468, 'MP', 'Northern Mariana Islands', 'Северные Марианские о-ва', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3569794, 'MQ', 'Martinique', 'Мартиника', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2377450, 'MR', 'Mauritania', 'Мавритания', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3578037, 'MS', 'Montserrat', 'Монсеррат', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2562247, 'MT', 'Malta', 'Мальта', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (933945, 'MU', 'Mauritius', 'Маврикий', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1282027, 'MV', 'Maldives', 'Мальдивские о-ва', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (927384, 'MW', 'Malawi', 'Малави', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3482970, 'MX', 'Mexico', 'Мексика', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1222391, 'MY', 'Malaysia', 'Малайзия', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1024552, 'MZ', 'Mozambique', 'Мозамбик', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (877031, 'NA', 'Namibia', 'Намибия', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2138981, 'NC', 'New Caledonia', 'Новая Каледония', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2440476, 'NE', 'Niger', 'Нигер', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2155115, 'NF', 'Norfolk Island', 'Остров Норфолк', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2317765, 'NG', 'Nigeria', 'Нигерия', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3616349, 'NI', 'Nicaragua', 'Никарагуа', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2743477, 'NL', 'Netherlands', 'Нидерланды', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (777019, 'NO', 'Norway', 'Норвегия', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1282684, 'NP', 'Nepal', 'Непал', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2110425, 'NR', 'Nauru', 'Науру', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (4036232, 'NU', 'Niue', 'Ниуе', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2178933, 'NZ', 'New Zealand', 'Новая Зеландия', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (286282, 'OM', 'Oman', 'Оман', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3700038, 'PA', 'Panama', 'Панама', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3690602, 'PE', 'Peru', 'Перу', 7);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (4030656, 'PF', 'French Polynesia', 'Французская Полинезия', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2083537, 'PG', 'Papua New Guinea', 'Папуа – Новая Гвинея', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1679435, 'PH', 'Philippines', 'Филиппины', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1108175, 'PK', 'Pakistan', 'Пакистан', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (707872, 'PL', 'Poland', 'Польша', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3424932, 'PM', 'Saint Pierre and Miquelon', 'Сен-Пьер и Микелон', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (4030699, 'PN', 'Pitcairn Islands', 'Питкэрн', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (4562485, 'PR', 'Puerto Rico', 'Пуэрто-Рико', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (281133, 'PS', 'Palestine', 'Палестинские территории', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2261447, 'PT', 'Portugal', 'Португалия', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1559582, 'PW', 'Palau', 'Палау', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3436583, 'PY', 'Paraguay', 'Парагвай', 7);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (289523, 'QA', 'Qatar', 'Катар', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (935157, 'RE', 'Réunion', 'Реюньон', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (662161, 'RO', 'Romania', 'Румыния', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (783814, 'RS', 'Serbia', 'Сербия', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (452949, 'RU', 'Russia', 'Россия', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (49518, 'RW', 'Rwanda', 'Руанда', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (100425, 'SA', 'Saudi Arabia', 'Саудовская Аравия', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2103350, 'SB', 'Solomon Islands', 'Соломонские острова', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (241131, 'SC', 'Seychelles', 'Сейшельские о-ва', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (365139, 'SD', 'Sudan', 'Судан', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (601901, 'SE', 'Sweden', 'Швеция', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1880159, 'SG', 'Singapore', 'Сингапур', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3370684, 'SH', 'Saint Helena', 'Остров Святой Елены', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3186270, 'SI', 'Slovenia', 'Словения', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (607072, 'SJ', 'Svalbard and Jan Mayen', 'Свальбард и Ян-Майен', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (723064, 'SK', 'Slovak Republic', 'Словакия', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2403846, 'SL', 'Sierra Leone', 'Сьерра-Леоне', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3166645, 'SM', 'San Marino', 'Сан-Марино', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2244979, 'SN', 'Senegal', 'Сенегал', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (51537, 'SO', 'Somalia', 'Сомали', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3382783, 'SR', 'Suriname', 'Суринам', 7);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (373303, 'SS', 'South Sudan', 'Южный Судан', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2410758, 'ST', 'São Tomé and Príncipe', 'Сан-Томе и Принсипе', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3582790, 'SV', 'El Salvador', 'Сальвадор', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3513392, 'SX', 'Sint Maarten', 'Синт-Мартен', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (163843, 'SY', 'Syria', 'Сирийская Арабская Республика', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (934841, 'SZ', 'Swaziland', 'Свазиленд', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3576916, 'TC', 'Turks and Caicos Islands', 'Острова Тёркс и Кайкос', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (245785, 'TD', 'Chad', 'Чад', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1546102, 'TF', 'French Southern Territories', 'Французские Южные Территории', 2);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2363686, 'TG', 'Togo', 'Того', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1117578, 'TH', 'Thailand', 'Тайланд', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1220409, 'TJ', 'Tajikistan', 'Таджикистан', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (4031074, 'TK', 'Tokelau', 'Токелау', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1645457, 'TL', 'East Timor', 'Восточный Тимор', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (162183, 'TM', 'Turkmenistan', 'Туркменистан', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2464020, 'TN', 'Tunisia', 'Тунис', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (4032279, 'TO', 'Tonga', 'Тонга', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (295902, 'TR', 'Turkey', 'Турция', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3573523, 'TT', 'Trinidad and Tobago', 'Тринидад и Тобаго', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2110297, 'TV', 'Tuvalu', 'Тувалу', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1665196, 'TW', 'Taiwan', 'Тайвань', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (148730, 'TZ', 'Tanzania', 'Танзания', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (616743, 'UA', 'Ukraine', 'Украина', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (226074, 'UG', 'Uganda', 'Уганда', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (5854968, 'UM', 'U.S. Minor Outlying Islands', 'Внешние малые острова (США)', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (4046230, 'US', 'United States', 'США', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3439608, 'UY', 'Uruguay', 'Уругвай', 7);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1114928, 'UZ', 'Uzbekistan', 'Узбекистан', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3164670, 'VA', 'Vatican City', 'Ватикан', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3577795, 'VC', 'Saint Vincent and the Grenadines', 'Сент-Винсент и Гренадины', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3480908, 'VE', 'Venezuela', 'Венесуэла', 7);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (3577430, 'VG', 'British Virgin Islands', 'Британские Виргинские о-ва', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (4795479, 'VI', 'U.S. Virgin Islands', 'Виргинские о-ва (США)', 5);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (1559969, 'VN', 'Vietnam', 'Вьетнам', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (2134431, 'VU', 'Vanuatu', 'Вануату', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (4034749, 'WF', 'Wallis and Futuna', 'Уоллис и Футуна', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (4034894, 'WS', 'Samoa', 'Самоа', 6);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (784097, 'XK', 'Kosovo', 'Косово', 4);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (69543, 'YE', 'Yemen', 'Йемен', 3);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (921688, 'YT', 'Mayotte', 'Майотта', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (936374, 'ZA', 'South Africa', 'ЮАР', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (175499, 'ZM', 'Zambia', 'Замбия', 1);
INSERT INTO `amotormag.loc`.geo_country (fgi_id, code, name, name_ru, continent_id) VALUES (878675, 'ZW', 'Zimbabwe', 'Зимбабве', 1);